USE Company;
/*Problem 1 to 10 is solved.*/
SELECT * FROM STAFF;
SELECT FNAME, LNAME, SALARY FROM STAFF;
SELECT PROPERTY_ID FROM VIEWING;

SELECT P.PROPERTY_ID , P.STREET, P.CITY, P.POSTAL_CODE, P.PROPERTY_TYPE, P.ROOMS, P.RENT, P.OWNER_ID FROM VIEWING AS V 
INNER JOIN PROPERTY_FOR_RENT AS P
ON V.PROPERTY_ID = P.PROPERTY_ID
WHERE COMMENT = 'LIKED';

SELECT FNAME, LNAME, SALARY/12 FROM STAFF;
SELECT FNAME, LNAME, SALARY FROM STAFF WHERE SALARY >10000;
SELECT CONCAT( STREET," ", CITY ,"-", POSTAL_CODE) AS Address FROM BRANCH WHERE CITY IN ('London','Glasgow');
SELECT FNAME, LNAME, SALARY/12 AS SALARY FROM STAFF WHERE (SALARY/12 BETWEEN 20000 AND 30000 );
SELECT POSITION,FNAME, LNAME FROM STAFF WHERE POSITION IN ('Manager','Superviser');

SELECT V.CLIENT_ID ,V.PROPERTY_ID ,P.PROPERTY_TYPE, V.VIEW_DATE 
FROM VIEWING AS V
INNER JOIN PROPERTY_FOR_RENT AS P
ON V.PROPERTY_ID = P.PROPERTY_ID
WHERE (P.PROPERTY_TYPE = 'PG4' && V.COMMENT IS NULL );

/*Problem 11 to 21 is solved.*/

SELECT SALARY FROM STAFF ORDER BY SALARY DESC;
SELECT * FROM PRIVATE_OWNER WHERE ADDRESS = 'Glasgow';
SELECT DISTINCT(PROPERTY_TYPE) FROM PROPERTY_FOR_RENT;
UPDATE STAFF SET SALARY = SALARY * 1.003 WHERE STAFF_ID IS NOT NULL;
UPDATE STAFF SET SALARY = SALARY * 1.005 WHERE POSITION = 'Manager';
UPDATE STAFF SET SALARY = 18000*12, POSITION = 'Manager' WHERE STAFF_ID = 'SG14';
SELECT FNAME, LNAME, BRANCH_ID FROM STAFF WHERE SEX = 'm';

DELETE V FROM VIEWING AS V INNER JOIN PROPERTY_FOR_RENT AS P
ON V.PROPERTY_ID = P.PROPERTY_ID
WHERE P.PROPERTY_TYPE='PG4';

DELETE FROM VIEWING;
SELECT FNAME, LNAME, MAXRENT FROM CLIENT_TABLE WHERE MAXRENT<8000;
SELECT FNAME, LNAME, SALARY FROM STAFF WHERE SEX = 'f' && BRANCH_ID='B010';